name: 오늘 날짜 추가

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  schedule:
    - cron: '0 0 * * *' # 매일 오전 9시(UTC+09:00 고려)에 실행

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 시간 추가
        run: |
          echo "## 업데이트 시간" >> README.md
          echo "$(date +'%Y-%m-%d %H:%M:%S')" >> README.md

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions@users.noreply.github.com'
          git add .
          git commit -m '오늘 날짜 추가'
          git push
